baseURL = "/"
languageCode = "en-us"
title = "Quincy's Land"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  logo = "img/logo.png"

  [params.homepage_meta_tags]
    meta_description = "Quincy searches the country for the best land deals and shares them with you!"
    meta_og_title = "Quincy's Land"
    meta_og_type = "website"
    meta_og_url = "https://quincysland.com"
    meta_og_image = "static/img/quincys_logo.png"
    meta_og_description = "Quincy searches the country for the best land deals and shares them with you!"
#    meta_twitter_card = "summary"
#    meta_twitter_site = "@zerostaticio"
#    meta_twitter_creator = "@zerostaticio"

# [[menu.main]]
#	name = "Services"
#	url = "/services/"
#    weight = 1

[[menu.main]]
    name = "Properties"
    url = "/properties/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
